name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - name: ubuntu-latest
            vexe: v
          - name: macos-latest
            vexe: v
          - name: windows-latest]
            vexe: v.exe
    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V on Windows
        if: ${{ matrix.os.name == 'windows-latest' }}
        run: |
          .\make.bat
          .\v.exe symlink
      
      - name: Build V on Ubuntu, MacOS
        if: ${{ matrix.os.name != 'windows-latest' }}
        run: |
          make
          sudo ./v symlink

      - name: Checkout Geo
        uses: actions/checkout@v2
        with:
          path: geo

      - name: Check if code is formatted
        run: |
          ${{ matrix.os.vexe }} fmt -verify geo

      - name: Build Geo
        run: |
          ${{ matrix.os.vexe }} -prod geo

      - name: Run Tests
        run: |
          ${{ matrix.os.vexe }} test geo
