name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout Geo
        uses: actions/checkout@v2
        with:
          path: geo

      - name: Build Geo
        run: |
          v -prod geo

      - name: Run Tests
        run: |
          v test geo
