name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Clone and build current V
        run: git clone https://github.com/vlang/v.git --depth=1 && cd v && make -j4
      
      - name: Check formatting
        run: ./v/v fmt -c

      - name: Run all unit tests
        run: ./v/v test .
