name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            make: make
          - name: macos-latest
            make: make
          - name: windows-latest
            make: .\make.bat
    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Check if code is formatted
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Build ${{ github.event.repository.name }}
        run: |
          v -prod .

      - name: Run Tests
        run: |
          v test .
        env:
          VJOBS: 1
