name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            vexe: v
          - name: macos-latest
            vexe: v
          - name: windows-latest
            vexe: v.exe
    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V on Windows
        if: ${{ matrix.os.name == 'windows-latest' }}
        shell: pwsh
        # Note 1: See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
        # for more information on how to add a location to PATH
        # Note 2: Chocolatey comes preinstalled so we can use refreshenv.
        run: |
          .\make.bat
          echo $pwd | Out-File -FilePath $env:GITHUB_PATH -Append
          refreshenv

      - name: Build V on Ubuntu, MacOS
        if: ${{ matrix.os.name != 'windows-latest' }}
        run: |
          make
          sudo ./v symlink

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
        with:
          path: cloned-${{ github.event.repository.name }}

      - name: Check if code is formatted
        run: |
          ${{ matrix.os.vexe }} fmt -diff cloned-${{ github.event.repository.name }}
          ${{ matrix.os.vexe }} fmt -verify cloned-${{ github.event.repository.name }}

      - name: Build ${{ github.event.repository.name }}
        run: |
          ${{ matrix.os.vexe }} -prod cloned-${{ github.event.repository.name }}

      - name: Run Tests
        run: |
          cd cloned-${{ github.event.repository.name }}
          ${{ matrix.os.vexe }} test .
