name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          ./make.bat
          ./v symlink
      
      - name: Build V on Ubuntu, MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          make
          sudo ./v symlink

      - name: Checkout Geo
        uses: actions/checkout@v2
        with:
          path: geo

      - name: Check if code is formatted
        run: |
          v fmt -verify geo

      - name: Build Geo
        run: |
          v -prod geo

      - name: Run Tests
        run: |
          v test geo
